trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
  - stage: Build
  jobs:
  - job: 'Build'
  steps:
- task: ServiceNow-DevOps-Agent-Job-Notification@1
  inputs:
    connectedServiceName: 'DevOps Connection'
    Phase: 'STARTED'
- task: ServiceNow-DevOps-Config-Agent-Register-Changeset@1
  inputs:
    connectedServiceName: 'DevOps Connection'
    changesetId: '123'
