# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
  - stage: Build
    jobs:
    - job: 'Commit'
      steps: 
      - task: ServiceNow-DevOps-Agent-Job-Notification@1
        inputs:
          connectedServiceName: 'empceverdingsd-Test-ServiceNow DevOps Service Connection'
          Phase: 'STARTED'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo 'Hello world changed 2'
      - task: ServiceNow-DevOps-Agent-Job-Notification@1
        inputs:
          connectedServiceName: 'empceverdingsd-Test-ServiceNow DevOps Service Connection'
          Phase: 'COMPLETED'

  - stage: Deploy_UAT
    jobs:
    - job: approval
      pool: server
      steps: 
      - task: ServiceNow-DevOps-Server-Change-Acceleration@1
        inputs:
          connectedServiceName: 'empceverdingsd-Test-ServiceNow DevOps Service Connection'