# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
  - stage: Build
    jobs:
    - job: 'Commit'
      steps: 
      - task: ServiceNow-DevOps-Agent-Job-Notification@1
        inputs:
          connectedServiceName: 'empceverdingsd-Test-ServiceNow DevOps Service Connection'
          Phase: 'STARTED'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo 'Hello world'
      - task: ServiceNow-DevOps-Agent-Job-Notification@1
        inputs:
          connectedServiceName: 'empceverdingsd-Test-ServiceNow DevOps Service Connection'
          Phase: 'COMPLETED'

  - stage: Deploy_UAT
    jobs:
    - job: approval
      pool: server
      steps: 
      - task: ServiceNow-DevOps-Server-Change-Acceleration@1
        inputs:
          connectedServiceName: 'empceverdingsd-Test-ServiceNow DevOps Service Connection'
        condition: true
      - task: InvokeRESTAPI@1
        inputs:
          connectionType: 'connectedServiceName'
          serviceConnection: 'empceverdingsd-Test-ServiceNow DevOps Service Connection'
          method: 'GET'
          urlSuffix: 'api/sn_devops/devops/orchestration/changeInfo?stageName=Deploy_UAT%2Fapproval&pipelineName=Test%2FMrChrisE.testfromADO&toolId=d30ba9c0db63f010b8f92ebbd39619ce&buildNumber=$(build.buildId)'
          waitForCompletion: 'true'